-- Step 7: Real station operator identity and station assignment.
-- A station operator is an existing `users` record linked to exactly one station.

create table if not exists public.station_operators (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    station_id bigint not null references public.fuel_stations(id) on delete restrict,
    operator_code varchar(50) not null unique,
    status varchar(20) not null default 'active',
    last_login_at timestamptz null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint station_operators_status_check
        check (status in ('active', 'inactive', 'suspended')),
    constraint station_operators_user_unique
        unique (user_id)
);

create index if not exists idx_station_operators_station_id
    on public.station_operators(station_id);

create index if not exists idx_station_operators_operator_code
    on public.station_operators(operator_code);

-- Backend uses the service-role key, so RLS is not required for this table in
-- the current trusted-server architecture. Enable RLS later if client access
-- is added directly to Supabase.
