-- Dedicated station operator accounts.
-- One operator identity belongs to one station.
-- A user account is still stored in users for common identity fields.

CREATE TABLE IF NOT EXISTS station_operators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    station_id BIGINT NOT NULL REFERENCES fuel_stations(id) ON DELETE RESTRICT,
    operator_code VARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    last_login_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT station_operators_status_check
      CHECK (status IN ('active', 'inactive', 'suspended')),

    CONSTRAINT station_operators_user_unique
      UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_station_operators_station_id
    ON station_operators(station_id);

CREATE INDEX IF NOT EXISTS idx_station_operators_operator_code
    ON station_operators(operator_code);

-- Keep updated_at current.
CREATE OR REPLACE FUNCTION set_station_operator_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_station_operator_updated_at
ON station_operators;

CREATE TRIGGER trg_station_operator_updated_at
BEFORE UPDATE ON station_operators
FOR EACH ROW
EXECUTE FUNCTION set_station_operator_updated_at();
