-- Step 9: Fuel pricing + transaction price snapshot
-- NOTE: 2000 MMK/L is a DEVELOPMENT seed value only. Replace it with
-- an administrator-managed price before real-world deployment.

ALTER TABLE public.vehicles
    ADD COLUMN IF NOT EXISTS fuel_type VARCHAR(30);

UPDATE public.vehicles
SET fuel_type = 'petrol_92'
WHERE fuel_type IS NULL OR btrim(fuel_type) = '';

ALTER TABLE public.vehicles
    ALTER COLUMN fuel_type SET DEFAULT 'petrol_92';

CREATE TABLE IF NOT EXISTS public.fuel_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fuel_type VARCHAR(30) NOT NULL,
    price_per_liter NUMERIC(12,2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'MMK',
    effective_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    effective_to TIMESTAMPTZ NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fuel_prices_price_positive CHECK (price_per_liter > 0),
    CONSTRAINT fuel_prices_status_check CHECK (status IN ('active', 'inactive'))
);

CREATE INDEX IF NOT EXISTS idx_fuel_prices_lookup
    ON public.fuel_prices(fuel_type, status, effective_from DESC);

ALTER TABLE public.fuel_transactions
    ADD COLUMN IF NOT EXISTS fuel_type VARCHAR(30);

ALTER TABLE public.fuel_transactions
    ADD COLUMN IF NOT EXISTS unit_price NUMERIC(12,2);

-- Backfill existing transaction snapshots from the current vehicle type.
-- Existing rows remain nullable-safe if the vehicle row cannot be resolved.
UPDATE public.fuel_transactions ft
SET fuel_type = COALESCE(ft.fuel_type, v.fuel_type, 'petrol_92')
FROM public.vehicles v
WHERE v.id = ft.vehicle_id
  AND (ft.fuel_type IS NULL OR btrim(ft.fuel_type) = '');

UPDATE public.fuel_transactions
SET fuel_type = 'petrol_92'
WHERE fuel_type IS NULL OR btrim(fuel_type) = '';

UPDATE public.fuel_transactions
SET unit_price = CASE
    WHEN liters_pumped > 0 AND amount_paid IS NOT NULL
    THEN ROUND(amount_paid / liters_pumped, 2)
    ELSE NULL
END
WHERE unit_price IS NULL;

-- Development seed. This value is the project's previous hard-coded fallback,
-- not a claim about a current market/government fuel price.
INSERT INTO public.fuel_prices (
    fuel_type,
    price_per_liter,
    currency,
    effective_from,
    status
)
SELECT
    'petrol_92',
    2000.00,
    'MMK',
    NOW(),
    'active'
WHERE NOT EXISTS (
    SELECT 1
    FROM public.fuel_prices
    WHERE fuel_type = 'petrol_92'
      AND status = 'active'
);
