-- Step 10: Official vehicle registry controlled by the admin/authority.
-- A user may later claim only a vehicle in this table with status='approved'.
CREATE TABLE IF NOT EXISTS public.admin_vehicle_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_no VARCHAR(50) NOT NULL UNIQUE,
    plate_number VARCHAR(20) NOT NULL UNIQUE,
    owner_name VARCHAR(150) NOT NULL,
    owner_national_id VARCHAR(100),
    vehicle_type VARCHAR(50) NOT NULL,
    engine_capacity VARCHAR(20),
    fuel_type VARCHAR(30) NOT NULL DEFAULT 'petrol_92',
    weekly_quota NUMERIC(10,2) NOT NULL DEFAULT 20.00,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    approved_at TIMESTAMPTZ,
    approved_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT admin_vehicle_registry_status_check
      CHECK (status IN ('pending','approved','rejected','suspended')),
    CONSTRAINT admin_vehicle_registry_quota_check
      CHECK (weekly_quota >= 0)
);

CREATE INDEX IF NOT EXISTS idx_admin_vehicle_registry_status
    ON public.admin_vehicle_registry(status);
CREATE INDEX IF NOT EXISTS idx_admin_vehicle_registry_plate
    ON public.admin_vehicle_registry(plate_number);

CREATE OR REPLACE FUNCTION public.set_admin_vehicle_registry_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_admin_vehicle_registry_updated_at
ON public.admin_vehicle_registry;

CREATE TRIGGER trg_admin_vehicle_registry_updated_at
BEFORE UPDATE ON public.admin_vehicle_registry
FOR EACH ROW
EXECUTE FUNCTION public.set_admin_vehicle_registry_updated_at();
