-- Step 10.1: Central quota policy by vehicle_type + fuel_type.
-- Admin sets the official weekly entitlement here. Vehicle registry records
-- receive their quota from this policy; the vehicle form never accepts a
-- user-entered quota.
CREATE TABLE IF NOT EXISTS public.fuel_quota_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_type VARCHAR(50) NOT NULL,
    fuel_type VARCHAR(30) NOT NULL,
    weekly_quota_liters NUMERIC(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    effective_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    effective_to TIMESTAMPTZ,
    created_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fuel_quota_policies_quota_check
      CHECK (weekly_quota_liters >= 0),
    CONSTRAINT fuel_quota_policies_status_check
      CHECK (status IN ('active','inactive')),
    CONSTRAINT fuel_quota_policies_effective_dates_check
      CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT fuel_quota_policies_type_fuel_unique
      UNIQUE (vehicle_type, fuel_type)
);

CREATE INDEX IF NOT EXISTS idx_fuel_quota_policies_status
    ON public.fuel_quota_policies(status);

CREATE OR REPLACE FUNCTION public.set_fuel_quota_policies_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_fuel_quota_policies_updated_at
ON public.fuel_quota_policies;

CREATE TRIGGER trg_fuel_quota_policies_updated_at
BEFORE UPDATE ON public.fuel_quota_policies
FOR EACH ROW
EXECUTE FUNCTION public.set_fuel_quota_policies_updated_at();

-- Development/default policies. Admin can change these later.
INSERT INTO public.fuel_quota_policies
    (vehicle_type, fuel_type, weekly_quota_liters, status)
VALUES
    ('car', 'petrol_92', 20.00, 'active'),
    ('car', 'petrol_95', 20.00, 'active'),
    ('car', 'diesel',    20.00, 'active'),
    ('bike', 'petrol_92', 10.00, 'active'),
    ('bike', 'petrol_95', 10.00, 'active'),
    ('three_wheel', 'petrol_92', 15.00, 'active'),
    ('bus', 'diesel', 100.00, 'active'),
    ('truck', 'diesel', 150.00, 'active')
ON CONFLICT (vehicle_type, fuel_type) DO NOTHING;
